server:
  port: 8084
feign:
  okhttp:
    enabled: true # 开启okhttp的feign底层请求调用客户端为okhttp

hm:
  db:
    database: hm-trade
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller

spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://localhost:8090
      http-method-specify: true # 开启请求方式前缀
  # 配置rabbitmq
  rabbitmq:
    host: 192.168.100.128 # rabbitmq地址
    port: 5672 # 代码连接端口，如果是网页访问端口是15672
    virtual-host: /hmall # 虚拟主机
    username: hmall
    password: 123


seata:
  data-source-proxy-mode: AT
