server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启okhttp的feign底层请求调用客户端为okhttp
  sentinel:
    enabled: true # 开启feign的sentinel支持

hm:
  db:
    database: hm-cart
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # sentinel控制台地址
      http-method-specify: true # 是否设置请求方式作为资源名

seata:
  data-source-proxy-mode: AT
